---

language: node_js
node_js:
  - node

cache:
  directories:
    - node_modules

script:
  - make lint
  - npm run build

deploy:
  provider: surge
  skip_cleanup: true
  domain: table.surge.sh
  project: ./build/
  on:
  branch: master